### ISSUE TITLE
Start of the code review process 👋

### ISSUE THREAD

**Issue by olivierobert** [kiattisakng9/nimble-mass-gsearch#1]
Hello Kia 👋 , thank you for your effort on the code submission. I am Olivier from Nimble, and I am happy to be the reviewer for our code review session.

During the review process, I would like to know more about your decisions and thus I will create issues where I think there could be more improvements regarding your performance here.

At the same time, please keep in mind that this is a bi-directional process and I would love to hear back from you as well. Therefore, don’t hesitate to raise your questions or share your opinions about the implementation (if any) during the process.

**Comment by olivierobert** [comment]
@kiattisakng9 I complete the round of code reviews. You can review them and provide your feedback.

Note that using pull requests to merge code was a requirement but you did not follow this instruction. Therefore, this will also impact the outcome negatively.

**Comment by kiattisakng9** [comment]
Thank you for your code review. I will provide my feedback for every issues that you have opened as soon as possible.

**Comment by olivierobert** [comment]
As you closed all issues, the code review process is now completed. Our team will provide you with our final feedback to you by email.

**Comment by kiattisakng9** [comment]
I understand and I admit to have missed out this point from the test requirement. Once again, I would like to thank you very much for the code review and the tips and resources that you have provided. I will be sure to do more research and to improve myself further.
