### ISSUE TITLE
[Chore] Update README with correct database instructions

### ISSUE THREAD

**Issue by olivierobert** [kiattisakng9/nimble-mass-gsearch#2]
## Issue

By following the README  file, it is not possible to set up the database for the project. Indeed, despite updating the file `.env`:

![image](https://user-images.githubusercontent.com/696529/171551003-a5d7c12d-c21c-4f30-bf75-a8d34874db1e.png)

The command `yarn migrate-db` fails.

## Expected

The README must provide instructions to also update the file `config.json`:

![image](https://user-images.githubusercontent.com/696529/171551115-a10496ad-506b-4dd4-8812-e09aabd275c2.png)

**Comment by kiattisakng9** [comment]
I must have miss out on this. Thank you very much for pointing this out for me.

**Comment by kiattisakng9** [comment]
I must have missed that point. It is my mistake. Thank you for pointing it out.
