### ISSUE TITLE
[Feature] Processing of keywords must be decoupled from the upload

### ISSUE THREAD

**Issue by olivierobert** [kiattisakng9/nimble-mass-gsearch#3]
## Issue

The search results are only inserted in the database if the Google search was successful. Most of the code is in the component https://github.com/kiattisakng9/nimble-mass-gsearch/blob/main/src/Pages/SearchComponents/CSVInput.js.

The processing is also synchronous with the upload, the more keywords uploaded, the longer the user will stay on the upload page.

💡 As a side note, the processing of the keywords should be the responsibility of the API. The business logic to validate keywords is a backend concern, not a frontend one.

## Expected

The code challenge requires the application to process up to 100 keywords, hence it is crucial to first create the keywords in the database. The upload would be very fast. Then process the scraping asynchronously. There lies the core difficulty of the code challenger, but unfortunately, it seems that you missed it 😭

**Comment by kiattisakng9** [comment]
Thank you very much for this comment. It is an eye-opener that it should be a backend concern and not the frontend one. I have always thought that the processing of the keywords should be done in the front end. It is my mistake and I will be sure to learn from it. I appreciate your feedback on this very much.
