### ISSUE TITLE
[Feature] API has no authentication

### ISSUE THREAD

**Issue by olivierobert** [kiattisakng9/nimble-mass-gsearch#4]
## Issue

Anyone can perform API requests against the API without being authorized. Below is a request made with Postman:

![image](https://user-images.githubusercontent.com/696529/171552251-4b0f56af-9bcd-4b99-b6c9-13bccfc673ad.png)

## Expected

The API must require authentication and the search results must be scope to the authenticated user.

**Comment by kiattisakng9** [comment]
I agree. I should have added API key authentication for making requests and only allow the requests to be made if the requestor is authenticated.
