### ISSUE TITLE
[Chore] Extract API controllers/handlers from routes 

### ISSUE THREAD

**Issue by olivierobert** [kiattisakng9/nimble-mass-gsearch#5]
## Issue

The backend application in `server` is using Express routes without controllers. While this works, it couples routing with business logic e.g., validations, authorization, etc. It also makes it hard to test.

## Expected

Instead, routes should only be concerned with redirecting the request to the appropriate handler method. You can refer to [MDN docs](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/routes#create_the_catalog_route_module) for more information.

On a side note, using a more full-fledged framework such as [NestJS](https://nestjs.com/) could have helped to cut some of the bootstrapping work while bringing a standard application structure. Under the hood, it remains Express but it comes with built-in features including security ones  💭

**Comment by kiattisakng9** [comment]
I did not have any experience and knowledge of implementing controllers into the backend application. I will be sure to learn more and research on this topic. Also, thank you very much for the additional information and resources that you have included in the issue.
