### ISSUE TITLE
[Feature] Extract components into their own directory

### ISSUE THREAD

**Issue by olivierobert** [kiattisakng9/nimble-mass-gsearch#6]
## Issue

The UI components are mixed with the code for pages, making it hard for code discovery but also for reusability of components.

## Expected

Components and pages should be separated:

```
├── src
│   ├── Components 
│   ├── Contexts 
│   ├── Pages 
```

Frameworks like Next.JS relies on such structure and it is a widely accepted standard 🏛️

**Comment by kiattisakng9** [comment]
Thank you for the advice. I will learn more about this framework and its benefits.
