### ISSUE TITLE
[Chore] Lack of automated tests

### ISSUE THREAD

**Issue by olivierobert** [kiattisakng9/nimble-mass-gsearch#7]
## Issue

As part of the code challenge, automated tests are required. However, there is neither unit of end-to-end tests.

## Expected

Based on the application structure, the following tests would be needed:
- Unit tests for the server application, especially for the scraping logic.
- Unit tests for React components
- UI tests for the critical user flows such as CSV upload and listing of keyword results. Note that using Cypress would be excpected.

**Comment by kiattisakng9** [comment]
I understand and acknowledge that it is one of the requirement of the challenge. I lack the experience and time to write said tests. It is my bad. Thank you for the feedback. I will learn more about automated unit testing.
